# Site Info

title: Grupo de Pesquisa em Jogos
description: >- # this means to ignore newlines until "url:"
  Grupo de Pesquisa em Jogos do ICMC.


# Site Settings

url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: /gpj # the subpath of your site, e.g. /blog
permalink: /:title
timezone: America/Sao_Paulo
mathjax: true # enables support for mathjax (LaTeX)


# Site Build

sass:
  sass_dir: _sass
  style: compressed


# Other Parameters

plugins:
  - jekyll-feed

collections:
  news:
    output: true
    permalink: /news/:name
  people:
    output: true
    permalink: /people/:name
  projects:
    output: true
    permalink: /projects/:name
  publications:
    output: true
    permalink: /publications/:name

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
